### PR TITLE
Add new properties

### PR DESCRIPTION
**Pull request by dcastrowa**
### Description:
The pull request adds the osm id property to challenge properties.

### Potential Impact:

This new enhancement will allow access to the osm id property in challenge properties.

### Unit Test Approach:
Tox

### Test Results:

Tests passed

### CODE REVIEW

**Comment by mattmanley** [comment]
@dcastrowa I think there may be some additional properties we want to add, but I'm not completely sure. I'm not seeing priority rules in the challenge model for instance.

**Comment by dcastrowa** [comment]
@mattmanley Not sure if priorities rules still needs to be added as a property with the new priority model you're working on?

**Comment by mattmanley** [comment]
@dcastrowa I think we should add the priority rule properties for a challenge. That way people can create a challenge model with priority rules by passing priority rule models to the parameters. Does that make sense?

**Comment by shawat94** [comment]
One property that we could bring in that would immediately extend functionality here is "remoteGeoJson", which can be used in the '/challenge' endpoint to create a challenge from a URL (something that can currently be done via the MR UI, but not by this client).

**Comment by dcastrowa** [comment]
@shawat94 Yes I agree. I believe Matt had listed that as an added property I forgot to add.

**Comment by mattmanley** [comment]
@shawat94 @dcastrowa Definitely open to having that as an additional property. I wasn't really sure what its use was to be honest.

**Pull request merged**
